### ISSUE TITLE
Question: Create, sign and broadcast raw transaction

### ISSUE THREAD

**Issue by cuhte3** [keeshux/BitcoinSPV#9]
First of all I'd like to say thanks for the great framework! I'm trying to figure out steps needed to create a raw transaction, sign it with wallet and broadcast to network. Could you please guide me through necessary steps? @keeshux

**Comment by cuhte3** [comment]
In case if someone need it, I use the code below: 

    WSAddress *address = WSAddressFromString(self.networkParameters, @"addressToSend");
    const uint64_t value = amountToSend;

    WSTransactionBuilder *builder = [wallet buildTransactionToAddress:address forValue:value fee:0 error:&error];

    WSSignedTransaction *tx = [wallet signedTransactionWithBuilder:builder error:&error];

    DDLogInfo(@"Tx: %@", tx);
    
    WSPeerGroup *peerGroup = [[WSPeerGroup alloc] initWithParameters:self.networkParameters];
    [peerGroup startConnections];
    [peerGroup publishTransaction:tx];

**Comment by keeshux** [comment]
Glad you found the way. Closing!
